---
- name: Install Apache
  yum: 
    name: httpd
    state: present
  notify: Start and enable apache


- name: Deploy custom index.html
  template:
    src: /home/ansible/Code-Killers/web-lb/roles/webservers/templates/index.html
    dest: /var/www/html/index.html
    mode: '0644'
