- name: Add port 80
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled

- name: Add http service to Firewalld
  firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes

- name: Add https service to Firewalld
  firewalld:
    service: https
    state: enabled
    permanent: yes
    immediate: yes
