---
- name: Insert data into MariaDB database
  hosts: databases
  become: yes
  vars:
    db_name: Code_Killers
    db_table: students
    db_user: root
    db_password: password
   
  tasks:

    - name: Ensure the database is created
      ansible.builtin.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"

    - name: Create a table in the database
      mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: |
          CREATE TABLE IF NOT EXISTS {{ db_table }} (
            name VARCHAR(255) NOT NULL,
            state VARCHAR(255) UNIQUE NOT NULL
          );

    - name: Create a states table in database
      mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        query: |
          CREATE TABLE IF NOT EXISTS states (
            States VARCHAR(255) NOT NULL,
            Population VARCHAR(50) NOT NULL,
            Climate TEXT NOT NULL,
            Cost_Of_Living VARCHAR(225) NOT NULL,
            Happyness_Score VARCHAR(225) NOT NULL,
            Ranking VARCHAR(50) NOT NULL
          );     
          

    - name: Insert values into the table ignoring duplicates
      community.mysql.mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: |
          INSERT IGNORE INTO students (name, state) VALUES
          ('Ferdows', 'Virginia!'),
          ('Eric', 'Maryland'),
          ('Abrar', 'Virginia'),
          ('Sameem', 'virginia?'),
          ('Iryna', 'Illinois'),
          ('Dilnoza', 'Florida'),
          ('Fariza', 'Pennsylvania');

    - name: Insert values into the table ignoring duplicates
      community.mysql.mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: |
          INSERT IGNORE INTO states (States, Population, Climate, Cost_Of_Living, Happyness_Score, Ranking) VALUES
          ('Florida', '22.2M', 'Hot/Humid', 'HIGH!', '59.31', '#9'),
          ('Virginia', '8.6M', 'Subtropical', 'HIGH!', '57.69', '#13'),
          ('Maryland', '6.1M', 'Moderate/Humid', 'HIGH!', '64.62', '#22'),
          ('Illinois', '12.5M', 'Cold/Rainy', 'HIGH!', '56.71', '#38'),
          ('Pennsylvania', '12.9M', 'Moderate/Humid', 'HIGH!', '53.96', '#40'); 

