---
- name: Configure servers
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  tasks:

    - name: Ensure PermitRootLogin is set to no in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes
      notify: 
        - Restart SSH

    - name: Remove SSH configuration file
      file:
        path: /etc/ssh/sshd_config.d/01-permitrootlogin.conf
        state: absent
      
    - name: Ensure firewall is enabled
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Disable SELinux in configuration file
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
        state: present

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Set password for all users to 'password'
      user:
        name: "{{ item }}"
        password: "{{ 'password' | password_hash('sha256') }}"
      loop: "{{ ansible_facts.get('passwd', ['ansible' , 'root' ]) }}"
      when: ansible_facts.get('passwd', ['ansible' , 'root' ]) is defined

    - name: Reboot the system
      reboot:
        reboot_timeout: 600

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted

